client_config_backend: settings
client_config:
  client_id: 601023463369-3c82s343anhqghfjji6ktddhancgb255.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True